# -----------------------------------------------------------------------------
# STAGE 1 — IAM deployer roles
#
# Run after environments/core/ has been applied. Creates the Terraform deployer
# roles that environments/dev/ assumes when deploying services.
#
# In CI this environment is applied by the ci-pipeline role (created in core/).
# For local development, use the bootstrap CLI:
#   uv run scripts/bootstrap.py migrate-state iam
# then run terraform with a backend.hcl generated by the CLI.
# -----------------------------------------------------------------------------

terraform {
  required_version = ">= 1.10"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }

  # Backend values are supplied via backend.hcl (local) or -backend-config
  # flags (CI). Do not add values here — this block must remain empty so the
  # repository stays template-pure.
  backend "s3" {}
}

provider "aws" {
  region = var.aws_region
}

data "aws_caller_identity" "current" {}
