# -----------------------------------------------------------------------------
# iam — IAM deployer roles
#
# Requires platform/core/ to have been applied first. Creates the Terraform
# deployer roles assumed by platform/registry/ and all environments.
#
# In CI this stack is applied by the ci-pipeline role (created in core/).
# For local development, use the bootstrap CLI:
#   uv run scripts/bootstrap.py migrate-state iam
# then run terraform with a backend.hcl generated by the CLI.
# -----------------------------------------------------------------------------

terraform {
  required_version = ">= 1.10"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }

  # Backend values are supplied via backend.hcl (local) or -backend-config
  # flags (CI). Do not add values here — this block must remain empty so the
  # repository stays template-pure.
  backend "s3" {}
}

provider "aws" {
  region = var.aws_region
}

data "aws_caller_identity" "current" {}

data "terraform_remote_state" "core" {
  backend = "s3"
  config = {
    bucket = "shared-services-tfstate-${data.aws_caller_identity.current.account_id}"
    key    = "core/terraform.tfstate"
    region = var.aws_region
  }
}
